### ISSUE TITLE
Can't get this to work...

### ISSUE THREAD

**Issue by EasyG0ing1** [digitalduke/otpauth-migration-decoder#2]
Helo, in the interest of brevity, I'll get right to the point:

1) I have a valid otpauth-migration://offline?data= string that I generated from my personal Google Authenticator app using the Google zxing library for Java to convert the QR image into its string format.

2) Here is the text from a terminal of my results trying to parse it with this script:

```bash
~/Google $git clone https://github.com/digitalduke/otpauth-migration-decoder
Cloning into 'otpauth-migration-decoder'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 108 (delta 51), reused 93 (delta 37), pack-reused 0
Receiving objects: 100% (108/108), 33.21 KiB | 1.04 MiB/s, done.
Resolving deltas: 100% (51/51), done.
~/Google $cd otpauth-migration-decoder/
~/Google/otpauth-migration-decoder $pip install protobuf
Collecting protobuf
  Downloading protobuf-3.19.1-cp310-cp310-macosx_10_9_universal2.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 4.4 MB/s
Installing collected packages: protobuf
Successfully installed protobuf-3.19.1
~/Google/otpauth-migration-decoder $cd src
~/Google/otpauth-migration-decoder/src $python decoder.py "otpauth-migration://offline?data=<deleted for security>"
Traceback (most recent call last):
  File "/Users/michael/Google/otpauth-migration-decoder/src/decoder.py", line 20, in <module>
    import click
ModuleNotFoundError: No module named 'click'
~/Google/otpauth-migration-decoder/src $
```

What am I doing wrong?

**Comment by sean-liu** [comment]
you need to do "pip install click" as well, and I somehow made it running, but encountered "invalid input", and my string is also acquired from google authenticator app. @EasyG0ing1 @digitalduke

**Comment by EasyG0ing1** [comment]
@sean-liu @digitalduke 

Based on [this pull request](https://github.com/digitalduke/otpauth-migration-decoder/pull/3), you have to engage the script like this, adding ```--convert``` before the encoded auth string:

```
python decoder.py --convert "otpauth-migration://offline?data=CjEKCkhlbGxvId6tvu8SGEV4YW1wbGU6YWxpY2VAZ29vZ2xlLmNvbRoHRXhhbXBsZTAC"
```

I tried it and it works!

**Comment by shalva97** [comment]
Also had such problems so I have made similar library, but completly in Kotlin: https://github.com/shalva97/google-auth-decode
